[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run watch"
  targetPort = 8080
  autoLaunch = false
  publish = "dist"

# [[redirects]]
#   from = "/what"
#   to = "/"
#   status = 302
#   force = true

# [[redirects]]
#   from = "/agentic"
#   to = "/"
#   status = 302
#   force = true

# [[redirects]]
#   from = "/work/*"
#   to = "/"
#   status = 302
#   force = true

