[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run watch"
  targetPort = 8080
  autoLaunch = false
  publish = "dist"

